# Note: This script should be run as Administrator for full functionality

<#
.SYNOPSIS
    Configures PowerShell profile with Starship prompt and useful settings.

.DESCRIPTION
    Sets up PowerShell profile with Starship initialization, useful aliases,
    PSReadLine configuration, and productivity enhancements.
    Supports dry-run mode via DRYRUN_MODE environment variable.

.EXAMPLE
    .\configure-powershell.ps1
#>

# Import common helpers
. "$PSScriptRoot\common-helpers.ps1"

function Test-DryRun {
    return ($env:DRYRUN_MODE -eq "true")
}

function Test-StarshipInstalled {
    try {
        $null = Get-Command starship -ErrorAction Stop
        return $true
    }
    catch {
        return $false
    }
}

function Get-PowerShellProfilePath {
    return $PROFILE.CurrentUserAllHosts
}

function Backup-Profile {
    param([string]$ProfilePath)

    if (Test-Path $ProfilePath) {
        $backupPath = "$ProfilePath.backup-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
        Write-ColorOutput "  Creating backup: $backupPath" "Yellow"
        Copy-Item -Path $ProfilePath -Destination $backupPath -Force
        return $true
    }
    return $false
}

function New-PowerShellProfile {
    $profilePath = Get-PowerShellProfilePath

    Write-ColorOutput "`nConfiguring PowerShell profile..." "Cyan"
    Write-ColorOutput "  Profile location: $profilePath" "Gray"

    if (Test-DryRun) {
        Write-DryRunAction "Create/update PowerShell profile at: $profilePath"
        return $true
    }

    # Create profile directory if it doesn't exist
    $profileDir = Split-Path -Parent $profilePath
    if (-not (Test-Path $profileDir)) {
        New-Item -Path $profileDir -ItemType Directory -Force | Out-Null
        Write-ColorOutput "  âś“ Created profile directory" "Green"
    }

    # Backup existing profile
    if (Test-Path $profilePath) {
        Backup-Profile -ProfilePath $profilePath
        Write-ColorOutput "  âś“ Backed up existing profile" "Green"
    }

    # Create new profile content
    $profileContent = @'
# ========================================
# PowerShell Profile Configuration
# Generated by opinionated_windows11 setup
# ========================================

# ========================================
# Starship Prompt
# ========================================
if (Get-Command starship -ErrorAction SilentlyContinue) {
    Invoke-Expression (&starship init powershell)
}
else {
    Write-Host "Starship not found. Install it with: winget install Starship.Starship" -ForegroundColor Yellow
}

# ========================================
# PSReadLine Configuration
# ========================================
if (Get-Module -ListAvailable -Name PSReadLine) {
    Import-Module PSReadLine

    # Enable predictive IntelliSense
    Set-PSReadLineOption -PredictionSource History
    Set-PSReadLineOption -PredictionViewStyle ListView

    # Enable syntax highlighting
    Set-PSReadLineOption -Colors @{
        Command = 'Cyan'
        Parameter = 'DarkCyan'
        String = 'Green'
        Operator = 'DarkGray'
    }

    # Set keyboard shortcuts
    Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete
    Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
    Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward

    # Enable history
    Set-PSReadLineOption -HistorySearchCursorMovesToEnd
    Set-PSReadLineOption -MaximumHistoryCount 10000
}

# ========================================
# Useful Aliases
# ========================================

# Navigation
function .. { Set-Location .. }
function ... { Set-Location ..\.. }
function .... { Set-Location ..\..\.. }

# Git shortcuts
function gs { git status }
function ga { git add $args }
function gc { git commit -m $args }
function gp { git push }
function gl { git pull }
function gd { git diff }
function gco { git checkout $args }
function gb { git branch }
function glog { git log --oneline --graph --decorate --all }

# Docker shortcuts
function d { docker $args }
function dc { docker-compose $args }
function dps { docker ps }
function dpsa { docker ps -a }
function di { docker images }

# System shortcuts
function ll { Get-ChildItem -Force }
function la { Get-ChildItem -Force -Hidden }
function which { param($command) Get-Command $command | Select-Object -ExpandProperty Definition }
function touch { param($file) New-Item -ItemType File -Path $file -Force | Out-Null }

# Quick edit profile
function Edit-Profile { code $PROFILE }
function Reload-Profile { . $PROFILE; Write-Host "Profile reloaded!" -ForegroundColor Green }

# Quick directory navigation
function dev { Set-Location "$env:USERPROFILE\DEV" }
function docs { Set-Location "$env:USERPROFILE\Documents" }
function downloads { Set-Location "$env:USERPROFILE\Downloads" }

# System information
function sysinfo {
    Write-Host "`n=== System Information ===" -ForegroundColor Cyan
    Write-Host "OS: " -NoNewline; (Get-CimInstance Win32_OperatingSystem).Caption
    Write-Host "Hostname: " -NoNewline; $env:COMPUTERNAME
    Write-Host "User: " -NoNewline; $env:USERNAME
    Write-Host "PowerShell: " -NoNewline; $PSVersionTable.PSVersion
    if (Get-Command node -ErrorAction SilentlyContinue) {
        Write-Host "Node.js: " -NoNewline; node --version
    }
    if (Get-Command git -ErrorAction SilentlyContinue) {
        Write-Host "Git: " -NoNewline; git --version
    }
    if (Get-Command python -ErrorAction SilentlyContinue) {
        Write-Host "Python: " -NoNewline; python --version
    }
    Write-Host ""
}

# WSL shortcut
function wsl-ubuntu { wsl -d Ubuntu }

# ========================================
# Environment Setup
# ========================================

# Set UTF-8 encoding
$OutputEncoding = [Console]::OutputEncoding = [Text.Encoding]::UTF8

# Enable case-sensitive tab completion (optional, uncomment if desired)
# Set-PSReadLineOption -CaseSensitive

# ========================================
# Greeting Message
# ========================================
function Show-Welcome {
    $hour = (Get-Date).Hour
    $greeting = if ($hour -lt 12) { "Good morning" }
                elseif ($hour -lt 18) { "Good afternoon" }
                else { "Good evening" }

    Write-Host "`n$greeting, " -NoNewline -ForegroundColor Cyan
    Write-Host "$env:USERNAME" -NoNewline -ForegroundColor Green
    Write-Host "! Welcome to PowerShell." -ForegroundColor Cyan
    Write-Host "Type 'sysinfo' for system information or 'Get-Alias' to see available shortcuts.`n" -ForegroundColor Gray
}

# Show welcome message on profile load
Show-Welcome

# ========================================
# Custom Functions
# ========================================

# Find files by pattern
function Find-File {
    param(
        [string]$Pattern,
        [string]$Path = "."
    )
    Get-ChildItem -Path $Path -Recurse -Filter $Pattern -ErrorAction SilentlyContinue
}

# Extract archives
function Extract-Archive {
    param([string]$File)

    if (-not (Test-Path $File)) {
        Write-Host "File not found: $File" -ForegroundColor Red
        return
    }

    $fullPath = (Resolve-Path $File).Path
    $destination = [System.IO.Path]::GetFileNameWithoutExtension($fullPath)

    Write-Host "Extracting $File to $destination..." -ForegroundColor Cyan
    Expand-Archive -Path $fullPath -DestinationPath $destination -Force
    Write-Host "Done!" -ForegroundColor Green
}
Set-Alias unzip Extract-Archive

# Get public IP
function Get-PublicIP {
    try {
        $ip = Invoke-RestMethod -Uri 'https://api.ipify.org?format=json' -TimeoutSec 5
        Write-Host "Public IP: " -NoNewline -ForegroundColor Cyan
        Write-Host $ip.ip -ForegroundColor Green
    }
    catch {
        Write-Host "Failed to get public IP" -ForegroundColor Red
    }
}

# Quick weather (optional - requires curl)
function Get-Weather {
    param([string]$City = "")

    if ($City) {
        curl "wttr.in/$City"
    }
    else {
        curl "wttr.in"
    }
}

# ========================================
# PATH Verification
# ========================================

# Verify important paths are in PATH
$pathsToCheck = @(
    "$env:USERPROFILE\.local\bin",
    "$env:LOCALAPPDATA\Programs\Microsoft VS Code\bin",
    "C:\Program Files\Git\cmd"
)

$missingPaths = @()
foreach ($pathToCheck in $pathsToCheck) {
    if (Test-Path $pathToCheck) {
        if ($env:PATH -notlike "*$pathToCheck*") {
            $missingPaths += $pathToCheck
        }
    }
}

if ($missingPaths.Count -gt 0) {
    Write-Host "`nWarning: Some paths are not in your PATH:" -ForegroundColor Yellow
    $missingPaths | ForEach-Object { Write-Host "  - $_" -ForegroundColor Gray }
    Write-Host "Run the environment setup script to fix this.`n" -ForegroundColor Yellow
}

# ========================================
# Additional Module Imports
# ========================================

# Import posh-git if available (Git integration)
if (Get-Module -ListAvailable -Name posh-git) {
    Import-Module posh-git
}

# ========================================
# End of Profile
# ========================================
'@

    try {
        Set-Content -Path $profilePath -Value $profileContent -Encoding UTF8 -Force
        Write-ColorOutput "  âś“ PowerShell profile created successfully" "Green"
        return $true
    }
    catch {
        Write-ColorOutput "  âś— Failed to create profile: $_" "Red"
        return $false
    }
}

function Install-PSReadLine {
    Write-ColorOutput "`nChecking PSReadLine module..." "Cyan"

    if (Test-DryRun) {
        Write-DryRunAction "Install/update PSReadLine module"
        return $true
    }

    try {
        $module = Get-Module -ListAvailable -Name PSReadLine | Sort-Object Version -Descending | Select-Object -First 1

        if ($module) {
            Write-ColorOutput "  â—‹ PSReadLine is already installed (version $($module.Version))" "Gray"
            return $true
        }
        else {
            Write-ColorOutput "  Installing PSReadLine module..." "Yellow"
            Install-Module -Name PSReadLine -Force -SkipPublisherCheck -AllowClobber
            Write-ColorOutput "  âś“ PSReadLine installed successfully" "Green"
            return $true
        }
    }
    catch {
        Write-ColorOutput "  âś— Failed to install PSReadLine: $_" "Red"
        return $false
    }
}

function New-StarshipConfig {
    $starshipConfigPath = "$env:USERPROFILE\.config\starship.toml"

    Write-ColorOutput "`nConfiguring Starship prompt..." "Cyan"

    if (Test-DryRun) {
        Write-DryRunAction "Create Starship config at: $starshipConfigPath"
        return $true
    }

    # Create .config directory if it doesn't exist
    $configDir = Split-Path -Parent $starshipConfigPath
    if (-not (Test-Path $configDir)) {
        New-Item -Path $configDir -ItemType Directory -Force | Out-Null
    }

    # Only create if it doesn't exist (don't overwrite user customizations)
    if (Test-Path $starshipConfigPath) {
        Write-ColorOutput "  â—‹ Starship config already exists (keeping user configuration)" "Gray"
        return $true
    }

    # Create a nice default Starship configuration
    $starshipConfig = @'
# Starship Configuration
# https://starship.rs/config/

format = """
[â”Śâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
[â”‚](bold green)$directory$git_branch$git_status
[â””â”€>](bold green) """

[character]
success_symbol = "[âžś](bold green)"
error_symbol = "[âś—](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold yellow"
conflicted = "âš”ď¸Ź "
ahead = "â‡ˇ${count}"
behind = "â‡Ł${count}"
diverged = "â‡•â‡ˇ${ahead_count}â‡Ł${behind_count}"
untracked = "đź¤·"
stashed = "đź“¦"
modified = "đź“ť"
staged = '[++\($count\)](green)'
renamed = "đź‘…"
deleted = "đź—‘"

[nodejs]
symbol = " "
style = "bold green"

[python]
symbol = " "
style = "bold yellow"

[rust]
symbol = " "
style = "bold red"

[docker_context]
symbol = " "
style = "bold blue"

[aws]
symbol = "  "
style = "bold yellow"

[golang]
symbol = " "
style = "bold cyan"
'@

    try {
        Set-Content -Path $starshipConfigPath -Value $starshipConfig -Encoding UTF8 -Force
        Write-ColorOutput "  âś“ Starship config created" "Green"
        return $true
    }
    catch {
        Write-ColorOutput "  âś— Failed to create Starship config: $_" "Red"
        return $false
    }
}

# Main execution
Write-ColorOutput "========================================" "Magenta"
Write-ColorOutput "  PowerShell Profile Configuration" "Magenta"
Write-ColorOutput "========================================" "Magenta"

$successCount = 0
$totalSteps = 0

# ========================================
# Check Starship Installation
# ========================================
Write-ColorOutput "`n[Step 1: Verify Starship]" "Cyan"
$totalSteps++

if (Test-StarshipInstalled) {
    Write-ColorOutput "  âś“ Starship is installed" "Green"
    $successCount++
}
else {
    Write-ColorOutput "  âś— Starship is not installed!" "Red"
    Write-ColorOutput "  Please install it first: winget install Starship.Starship" "Yellow"
    Write-ColorOutput "  Continuing with profile setup anyway..." "Gray"
}

# ========================================
# Install/Update PSReadLine
# ========================================
Write-ColorOutput "`n[Step 2: PSReadLine Module]" "Cyan"
$totalSteps++

if (Install-PSReadLine) {
    $successCount++
}

# ========================================
# Create PowerShell Profile
# ========================================
Write-ColorOutput "`n[Step 3: PowerShell Profile]" "Cyan"
$totalSteps++

if (New-PowerShellProfile) {
    $successCount++
}

# ========================================
# Create Starship Configuration
# ========================================
Write-ColorOutput "`n[Step 4: Starship Configuration]" "Cyan"
$totalSteps++

if (New-StarshipConfig) {
    $successCount++
}

# ========================================
# Summary
# ========================================
Write-ColorOutput "`n========================================" "Magenta"
Write-ColorOutput "  Configuration Summary" "Magenta"
Write-ColorOutput "========================================" "Magenta"
Write-ColorOutput "Total steps: $totalSteps" "White"
Write-ColorOutput "Successfully completed: $successCount" "Green"
Write-ColorOutput "Failed: $($totalSteps - $successCount)" "Red"

if ($successCount -eq $totalSteps) {
    Write-ColorOutput "`nPowerShell profile configured successfully!" "Green"
}
else {
    Write-ColorOutput "`nConfiguration completed with some warnings. Please check the output above." "Yellow"
}

# ========================================
# Next Steps
# ========================================
Write-ColorOutput "`n[Next Steps]" "Cyan"
Write-ColorOutput "  1. Close and reopen PowerShell to apply changes" "Yellow"
Write-ColorOutput "  2. Or reload the profile: . `$PROFILE" "Yellow"
Write-ColorOutput "  3. Type 'sysinfo' to test your new setup" "Yellow"
Write-ColorOutput "  4. Type 'Get-Alias' to see available shortcuts" "Yellow"
Write-ColorOutput "`n  Profile location: $(Get-PowerShellProfilePath)" "Gray"
Write-ColorOutput "  Edit with: code `$PROFILE" "Gray"
